---
title: "dataproc/ERR/2023_003"
linkTitle: "ERR/2023_003"
weight: 1
type: docs
description: >
  Dataproc cluster check IAM permission to launch cluster
---

**Product**: [Cloud Dataproc](https://cloud.google.com/dataproc)\
**Rule class**: ERR - Something that is very likely to be wrong

### Description
Dataproc cluster launch requires set of permissions to be enabled for the service account
that is used to create the cluster. If the required set of permissions are not
available, the cluster launch operation fails with
"Required <permission> permission for <resource>"

### Remediation
- You can check the output logs to check on the error. If you want to provide the permission
yo can navigate to cloud IAM console and provide the permissions.

  Log query example :

  resource.type="cloud_dataproc_cluster" \
  resource.labels.cluster_name="<dataproc-cluster-name>" \
  "Required <permission> permission for <resource>" \
  logName: "projects/<project-name>/logs/google.dataproc.agent"


### Further information
[DataProc IAM permissions](https://cloud.google.com/dataproc/docs/concepts/iam/iam)
